### PR TITLE
Add last modification date

### LINKED ISSUE #5: file revision/date code/issue version
need a quick method to determine if something has changed, both at a manifest level, and an alert level.

ie if a Fixed date has been added, there should be some version number/last changed date so the alert can be displayed to the user.

this way form the GCS i can check for items that have changed since a last view/acknowledged time. currently i would need to hash the content of each item and save it to check for modifications

### PR DESCRIPTION
**Pull request by stephendade**
This PR adds a "last modification date" at both a per-alert and entire manifest level.

- Each user alert will automatically have a "lastmodified" field added upon manifest generation. 
- A ``lastmodified.txt`` file will be uploaded alongside the manifest, containg the date&time of manifest generation

Fixes #5

### CODE REVIEW

**Comment by auturgy** [comment]
lgtm.  Needs a rebase before merge

**Review by auturgy — CHANGES_REQUESTED** [review]
rebase

**Comment by stephendade** [comment]
Now rebased

**Comment by stephendade** [comment]
Now rebased. Will merge.

**Pull request merged**
